/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Bouquet = IDL.Record({
  'timestamp' : Time,
  'flowers' : IDL.Vec(IDL.Text),
});
export const ProposalResponse = IDL.Record({
  'timestamp' : Time,
  'accepted' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getBouquet' : IDL.Func([], [Bouquet], ['query']),
  'getProposalResponse' : IDL.Func([], [IDL.Opt(ProposalResponse)], ['query']),
  'saveBouquet' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'saveProposalResponse' : IDL.Func([IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Bouquet = IDL.Record({
    'timestamp' : Time,
    'flowers' : IDL.Vec(IDL.Text),
  });
  const ProposalResponse = IDL.Record({
    'timestamp' : Time,
    'accepted' : IDL.Bool,
  });
  
  return IDL.Service({
    'getBouquet' : IDL.Func([], [Bouquet], ['query']),
    'getProposalResponse' : IDL.Func(
        [],
        [IDL.Opt(ProposalResponse)],
        ['query'],
      ),
    'saveBouquet' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'saveProposalResponse' : IDL.Func([IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };