/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'imageData' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
  'caption' : IDL.Text,
});
export const Letter = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
});
export const Bouquet = IDL.Record({
  'timestamp' : Time,
  'flowers' : IDL.Vec(IDL.Text),
});
export const WeddingCertificate = IDL.Record({
  'weddingDate' : IDL.Text,
  'bishalSigned' : IDL.Bool,
  'bishalSignedAt' : IDL.Opt(Time),
  'aasthaSignedAt' : IDL.Opt(Time),
  'aasthaSigned' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addFlowersForAastha' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'addFlowersForBishal' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'addHandwrittenNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addLetter' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteHandwrittenNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteLetter' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllHandwrittenNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllLetters' : IDL.Func([], [IDL.Vec(Letter)], ['query']),
  'getBouquetForAastha' : IDL.Func([], [Bouquet], ['query']),
  'getBouquetForBishal' : IDL.Func([], [Bouquet], ['query']),
  'getWeddingCertificate' : IDL.Func([], [WeddingCertificate], ['query']),
  'setWeddingDate' : IDL.Func([IDL.Text], [], []),
  'signWeddingCertificateAsAastha' : IDL.Func([], [], []),
  'signWeddingCertificateAsBishal' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'imageData' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
    'caption' : IDL.Text,
  });
  const Letter = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
  });
  const Bouquet = IDL.Record({
    'timestamp' : Time,
    'flowers' : IDL.Vec(IDL.Text),
  });
  const WeddingCertificate = IDL.Record({
    'weddingDate' : IDL.Text,
    'bishalSigned' : IDL.Bool,
    'bishalSignedAt' : IDL.Opt(Time),
    'aasthaSignedAt' : IDL.Opt(Time),
    'aasthaSigned' : IDL.Bool,
  });
  
  return IDL.Service({
    'addFlowersForAastha' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'addFlowersForBishal' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'addHandwrittenNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addLetter' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteHandwrittenNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteLetter' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllHandwrittenNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllLetters' : IDL.Func([], [IDL.Vec(Letter)], ['query']),
    'getBouquetForAastha' : IDL.Func([], [Bouquet], ['query']),
    'getBouquetForBishal' : IDL.Func([], [Bouquet], ['query']),
    'getWeddingCertificate' : IDL.Func([], [WeddingCertificate], ['query']),
    'setWeddingDate' : IDL.Func([IDL.Text], [], []),
    'signWeddingCertificateAsAastha' : IDL.Func([], [], []),
    'signWeddingCertificateAsBishal' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };