/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Bouquet {
    timestamp: Time;
    flowers: Array<string>;
}
export interface Letter {
    id: bigint;
    content: string;
    author: string;
    timestamp: Time;
}
export type Time = bigint;
export interface WeddingCertificate {
    weddingDate: string;
    bishalSigned: boolean;
    bishalSignedAt?: Time;
    aasthaSignedAt?: Time;
    aasthaSigned: boolean;
}
export interface Note {
    id: bigint;
    imageData: string;
    author: string;
    timestamp: Time;
    caption: string;
}
export interface backendInterface {
    addFlowersForAastha(flowers: Array<string>): Promise<void>;
    addFlowersForBishal(flowers: Array<string>): Promise<void>;
    addHandwrittenNote(author: string, imageData: string, caption: string): Promise<bigint>;
    addLetter(author: string, content: string): Promise<bigint>;
    deleteHandwrittenNote(id: bigint): Promise<boolean>;
    deleteLetter(id: bigint): Promise<boolean>;
    getAllHandwrittenNotes(): Promise<Array<Note>>;
    getAllLetters(): Promise<Array<Letter>>;
    getBouquetForAastha(): Promise<Bouquet>;
    getBouquetForBishal(): Promise<Bouquet>;
    getWeddingCertificate(): Promise<WeddingCertificate>;
    setWeddingDate(date: string): Promise<void>;
    signWeddingCertificateAsAastha(): Promise<void>;
    signWeddingCertificateAsBishal(): Promise<void>;
}
import type { Time as _Time, WeddingCertificate as _WeddingCertificate } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFlowersForAastha(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFlowersForAastha(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFlowersForAastha(arg0);
            return result;
        }
    }
    async addFlowersForBishal(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFlowersForBishal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFlowersForBishal(arg0);
            return result;
        }
    }
    async addHandwrittenNote(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHandwrittenNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHandwrittenNote(arg0, arg1, arg2);
            return result;
        }
    }
    async addLetter(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLetter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLetter(arg0, arg1);
            return result;
        }
    }
    async deleteHandwrittenNote(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHandwrittenNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHandwrittenNote(arg0);
            return result;
        }
    }
    async deleteLetter(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLetter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLetter(arg0);
            return result;
        }
    }
    async getAllHandwrittenNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHandwrittenNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHandwrittenNotes();
            return result;
        }
    }
    async getAllLetters(): Promise<Array<Letter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLetters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLetters();
            return result;
        }
    }
    async getBouquetForAastha(): Promise<Bouquet> {
        if (this.processError) {
            try {
                const result = await this.actor.getBouquetForAastha();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBouquetForAastha();
            return result;
        }
    }
    async getBouquetForBishal(): Promise<Bouquet> {
        if (this.processError) {
            try {
                const result = await this.actor.getBouquetForBishal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBouquetForBishal();
            return result;
        }
    }
    async getWeddingCertificate(): Promise<WeddingCertificate> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeddingCertificate();
                return from_candid_WeddingCertificate_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeddingCertificate();
            return from_candid_WeddingCertificate_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setWeddingDate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setWeddingDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWeddingDate(arg0);
            return result;
        }
    }
    async signWeddingCertificateAsAastha(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.signWeddingCertificateAsAastha();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signWeddingCertificateAsAastha();
            return result;
        }
    }
    async signWeddingCertificateAsBishal(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.signWeddingCertificateAsBishal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signWeddingCertificateAsBishal();
            return result;
        }
    }
}
function from_candid_WeddingCertificate_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeddingCertificate): WeddingCertificate {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weddingDate: string;
    bishalSigned: boolean;
    bishalSignedAt: [] | [_Time];
    aasthaSignedAt: [] | [_Time];
    aasthaSigned: boolean;
}): {
    weddingDate: string;
    bishalSigned: boolean;
    bishalSignedAt?: Time;
    aasthaSignedAt?: Time;
    aasthaSigned: boolean;
} {
    return {
        weddingDate: value.weddingDate,
        bishalSigned: value.bishalSigned,
        bishalSignedAt: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.bishalSignedAt)),
        aasthaSignedAt: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.aasthaSignedAt)),
        aasthaSigned: value.aasthaSigned
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
